version: '3.3'

services:
  adminer:
    container_name: adminer
    image: adminer:4-fastcgi
    restart: unless-stopped
    networks:
      - postgres
      - traefik
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.routers.adminer.service=adminer@docker"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.services.adminer.loadbalancer.server.port=9000"

volumes:
  adminer:
    driver: local

networks:
  postgres:
    external: true
  traefik:
    external: true