version: "3"

services:
  tournaments-migrations:
    image: registry.acc.rl-pool.com/next-id-migrations
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SHARD_ID=1
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    external: true
