version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /mnt/docker-volumes/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.svc.gweggemans.nl`)"
      - "traefik.http.routers.grafana.service=grafana@docker"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true