version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
      - .secrets.env
    networks:
      - postgres
    ports:
      - 5432:5432

volumes:
  postgres:
    driver: local

networks:
  postgres:
    name: postgres