version: '3.3'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    restart: unless-stopped
    networks:
      - postgres
      - traefik
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - .env
      - .secrets.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.svc.gweggemans.nl`)"
      - "traefik.http.routers.pgadmin.service=pgadmin@docker"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=8040"

volumes:
  pgadmin:
    driver: local

networks:
  postgres:
    external: true
  traefik:
    external: true